=== BombasticOctocat/Bomberman/src/main/resources/com/bombasticoctocat/bomberman/game/levels_configuration.xsd
<?xml version="1.0"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="bombermanLevelConfiguration"
           xmlns="bombermanLevelConfiguration"
           elementFormDefault="qualified">

  <xs:simpleType name="powerup">
    <xs:restriction base="xs:string">
      <xs:enumeration value="RANGE" />
      <xs:enumeration value="BOMB" />
      <xs:enumeration value="DETONATOR" />
      <xs:enumeration value="SPEED" />
      <xs:enumeration value="BOMBPASS" />
      <xs:enumeration value="WALLPASS" />
      <xs:enumeration value="FLAMEPASS" />
      <xs:enumeration value="MYSTERY" />
    </xs:restriction>
  </xs:simpleType>

  <xs:attributeGroup name="goombaAttributes">
    <xs:attribute name="level" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:integer">
          <xs:minInclusive value="0"/>
          <xs:maxInclusive value="7"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="amount" use="required" type="xs:positiveInteger"/>
  </xs:attributeGroup>

  <xs:element name="levelsConfiguration">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="levelConfiguration" minOccurs="1" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="bricksDensity" type="xs:double" />
              <xs:element name="powerup" type="powerup" />
              <xs:element name="penaltyGoomba">
                <xs:complexType>
                  <xs:attributeGroup ref="goombaAttributes"/>
                </xs:complexType>
              </xs:element>
              <xs:element name="goombas">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="goomba" minOccurs="1" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:attributeGroup ref="goombaAttributes"/>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="level" type="xs:positiveInteger" use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== BombasticOctocat/Bomberman/src/main/resources/com/bombasticoctocat/bomberman/game/levels_configuration.xml
<?xml version="1.0" encoding="UTF-8"?>

<levelsConfiguration xmlns="bombermanLevelConfiguration"
                     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                     xsi:schemaLocation="bombermanLevelConfiguration levels_configuration.xsd">
  <levelConfiguration level="1">
    <bricksDensity>0.25</bricksDensity>
    <powerup>RANGE</powerup>
    <penaltyGoomba level="7" amount="5"/>
    <goombas>
      <goomba level="0" amount="6"/>
    </goombas>
  </levelConfiguration>
  <levelConfiguration level="2">
    <bricksDensity>0.25</bricksDensity>
    <powerup>BOMB</powerup>
    <penaltyGoomba level="2" amount="5"/>
    <goombas>
      <goomba level="0" amount="3"/>
      <goomba level="1" amount="3"/>
    </goombas>
  </levelConfiguration>
  <levelConfiguration level="3">
    <bricksDensity>0.25</bricksDensity>
    <powerup>DETONATOR</powerup>
    <penaltyGoomba level="3" amount="5"/>
    <goombas>
      <goomba level="0" amount="2"/>
      <goomba level="1" amount="2"/>
      <goomba level="2" amount="2"/>
    </goombas>
  </levelConfiguration>
  <levelConfiguration level="4">
    <bricksDensity>0.25</bricksDensity>
    <powerup>SPEED</powerup>
    <penaltyGoomba level="3" amount="5"/>
    <goombas>
      <goomba level="0" amount="1"/>
      <goomba level="1" amount="1"/>
      <goomba level="2" amount="2"/>
      <goomba level="3" amount="2"/>
    </goombas>
  </levelConfiguration>
  <levelConfiguration level="5">
    <bricksDensity>0.25</bricksDensity>
    <powerup>BOMB</powerup>
    <penaltyGoomba level="3" amount="5"/>
    <goombas>
      <goomba level="1" amount="4"/>
      <goomba level="2" amount="3"/>
    </goombas>
  </levelConfiguration>
  <levelConfiguration level="6">
    <bricksDensity>0.25</bricksDensity>
    <powerup>BOMB</powerup>
    <penaltyGoomba level="3" amount="5"/>
    <goombas>
      <goomba level="1" amount="2"/>
      <goomba level="2" amount="3"/>
      <goomba level="3" amount="2"/>
    </goombas>
  </levelConfiguration>
  <levelConfiguration level="7">
    <bricksDensity>0.25</bricksDensity>
    <powerup>RANGE</powerup>
    <penaltyGoomba level="3" amount="5"/>
    <goombas>
      <goomba level="1" amount="2"/>
      <goomba level="2" amount="3"/>
      <goomba level="4" amount="2"/>
    </goombas>
  </levelConfiguration>
  <levelConfiguration level="8">
    <bricksDensity>0.25</bricksDensity>
    <powerup>DETONATOR</powerup>
    <penaltyGoomba level="3" amount="5"/>
    <goombas>
      <goomba level="1" amount="1"/>
      <goomba level="2" amount="2"/>
      <goomba level="3" amount="4"/>
    </goombas>
  </levelConfiguration>
  <levelConfiguration level="9">
    <bricksDensity>0.25</bricksDensity>
    <powerup>BOMBPASS</powerup>
    <penaltyGoomba level="3" amount="5"/>
    <goombas>
      <goomba level="1" amount="1"/>
      <goomba level="2" amount="1"/>
      <goomba level="3" amount="4"/>
      <goomba level="4" amount="1"/>
    </goombas>
  </levelConfiguration>
  <levelConfiguration level="10">
    <bricksDensity>0.25</bricksDensity>
    <powerup>WALLPASS</powerup>
    <penaltyGoomba level="3" amount="5"/>
    <goombas>
      <goomba level="1" amount="1"/>
      <goomba level="2" amount="1"/>
      <goomba level="3" amount="1"/>
      <goomba level="4" amount="3"/>
      <goomba level="5" amount="1"/>
    </goombas>
  </levelConfiguration>
  <levelConfiguration level="11">
    <bricksDensity>0.25</bricksDensity>
    <powerup>BOMB</powerup>
    <penaltyGoomba level="3" amount="5"/>
    <goombas>
      <goomba level="1" amount="1"/>
      <goomba level="2" amount="2"/>
      <goomba level="3" amount="3"/>
      <goomba level="4" amount="1"/>
      <goomba level="5" amount="1"/>
    </goombas>
  </levelConfiguration>
  <levelConfiguration level="12">
    <bricksDensity>0.25</bricksDensity>
    <powerup>BOMB</powerup>
    <penaltyGoomba level="3" amount="5"/>
    <goombas>
      <goomba level="1" amount="1"/>
      <goomba level="2" amount="1"/>
      <goomba level="3" amount="1"/>
      <goomba level="4" amount="4"/>
      <goomba level="5" amount="1"/>
    </goombas>
  </levelConfiguration>
  <levelConfiguration level="13">
    <bricksDensity>0.25</bricksDensity>
    <powerup>DETONATOR</powerup>
    <penaltyGoomba level="3" amount="5"/>
    <goombas>
      <goomba level="2" amount="3"/>
      <goomba level="3" amount="3"/>
      <goomba level="4" amount="3"/>
    </goombas>
  </levelConfiguration>
  <levelConfiguration level="14">
    <bricksDensity>0.25</bricksDensity>
    <powerup>BOMBPASS</powerup>
    <penaltyGoomba level="3" amount="5"/>
    <goombas>
      <goomba level="5" amount="7"/>
      <goomba level="6" amount="1"/>
    </goombas>
  </levelConfiguration>
  <levelConfiguration level="15">
    <bricksDensity>0.25</bricksDensity>
    <powerup>RANGE</powerup>
    <penaltyGoomba level="3" amount="5"/>
    <goombas>
      <goomba level="2" amount="1"/>
      <goomba level="3" amount="3"/>
      <goomba level="4" amount="3"/>
      <goomba level="6" amount="1"/>
    </goombas>
  </levelConfiguration>
  <levelConfiguration level="16">
    <bricksDensity>0.25</bricksDensity>
    <powerup>WALLPASS</powerup>
    <penaltyGoomba level="3" amount="5"/>
    <goombas>
      <goomba level="3" amount="3"/>
      <goomba level="4" amount="4"/>
      <goomba level="6" amount="1"/>
    </goombas>
  </levelConfiguration>
  <levelConfiguration level="17">
    <bricksDensity>0.25</bricksDensity>
    <powerup>BOMB</powerup>
    <penaltyGoomba level="3" amount="5"/>
    <goombas>
      <goomba level="2" amount="5"/>
      <goomba level="4" amount="2"/>
      <goomba level="6" amount="1"/>
    </goombas>
  </levelConfiguration>
  <levelConfiguration level="18">
    <bricksDensity>0.25</bricksDensity>
    <powerup>BOMBPASS</powerup>
    <penaltyGoomba level="3" amount="5"/>
    <goombas>
      <goomba level="0" amount="3"/>
      <goomba level="1" amount="3"/>
      <goomba level="6" amount="2"/>
    </goombas>
  </levelConfiguration>
  <levelConfiguration level="19">
    <bricksDensity>0.25</bricksDensity>
    <powerup>BOMB</powerup>
    <penaltyGoomba level="3" amount="5"/>
    <goombas>
      <goomba level="0" amount="1"/>
      <goomba level="1" amount="1"/>
      <goomba level="2" amount="3"/>
      <goomba level="5" amount="1"/>
      <goomba level="6" amount="2"/>
    </goombas>
  </levelConfiguration>
  <levelConfiguration level="20">
    <bricksDensity>0.25</bricksDensity>
    <powerup>DETONATOR</powerup>
    <penaltyGoomba level="3" amount="5"/>
    <goombas>
      <goomba level="1" amount="1"/>
      <goomba level="2" amount="1"/>
      <goomba level="3" amount="1"/>
      <goomba level="4" amount="2"/>
      <goomba level="5" amount="1"/>
      <goomba level="6" amount="2"/>
    </goombas>
  </levelConfiguration>
  <levelConfiguration level="21">
    <bricksDensity>0.25</bricksDensity>
    <powerup>BOMBPASS</powerup>
    <penaltyGoomba level="3" amount="5"/>
    <goombas>
      <goomba level="4" amount="4"/>
      <goomba level="5" amount="3"/>
      <goomba level="6" amount="2"/>
    </goombas>
  </levelConfiguration>
  <levelConfiguration level="22">
    <bricksDensity>0.25</bricksDensity>
    <powerup>DETONATOR</powerup>
    <penaltyGoomba level="3" amount="5"/>
    <goombas>
      <goomba level="2" amount="4"/>
      <goomba level="3" amount="3"/>
      <goomba level="4" amount="1"/>
      <goomba level="6" amount="1"/>
    </goombas>
  </levelConfiguration>
  <levelConfiguration level="23">
    <bricksDensity>0.25</bricksDensity>
    <powerup>BOMB</powerup>
    <penaltyGoomba level="3" amount="5"/>
    <goombas>
      <goomba level="2" amount="2"/>
      <goomba level="3" amount="2"/>
      <goomba level="4" amount="2"/>
      <goomba level="5" amount="2"/>
      <goomba level="6" amount="1"/>
    </goombas>
  </levelConfiguration>
  <levelConfiguration level="24">
    <bricksDensity>0.25</bricksDensity>
    <powerup>DETONATOR</powerup>
    <penaltyGoomba level="3" amount="5"/>
    <goombas>
      <goomba level="2" amount="1"/>
      <goomba level="3" amount="1"/>
      <goomba level="4" amount="4"/>
      <goomba level="5" amount="2"/>
      <goomba level="6" amount="1"/>
    </goombas>
  </levelConfiguration>
  <levelConfiguration level="25">
    <bricksDensity>0.25</bricksDensity>
    <powerup>BOMBPASS</powerup>
    <penaltyGoomba level="3" amount="5"/>
    <goombas>
      <goomba level="1" amount="2"/>
      <goomba level="2" amount="1"/>
      <goomba level="3" amount="1"/>
      <goomba level="4" amount="2"/>
      <goomba level="5" amount="2"/>
      <goomba level="6" amount="1"/>
    </goombas>
  </levelConfiguration>
  <levelConfiguration level="26">
    <bricksDensity>0.25</bricksDensity>
    <powerup>MYSTERY</powerup>
    <penaltyGoomba level="3" amount="5"/>
    <goombas>
      <goomba level="0" amount="1"/>
      <goomba level="1" amount="1"/>
      <goomba level="2" amount="1"/>
      <goomba level="3" amount="1"/>
      <goomba level="4" amount="2"/>
      <goomba level="5" amount="1"/>
      <goomba level="6" amount="1"/>
    </goombas>
  </levelConfiguration>
  <levelConfiguration level="27">
    <bricksDensity>0.25</bricksDensity>
    <powerup>RANGE</powerup>
    <penaltyGoomba level="3" amount="5"/>
    <goombas>
      <goomba level="0" amount="1"/>
      <goomba level="1" amount="1"/>
      <goomba level="4" amount="5"/>
      <goomba level="5" amount="1"/>
      <goomba level="6" amount="1"/>
    </goombas>
  </levelConfiguration>
  <levelConfiguration level="28">
    <bricksDensity>0.25</bricksDensity>
    <powerup>BOMB</powerup>
    <penaltyGoomba level="3" amount="5"/>
    <goombas>
      <goomba level="1" amount="1"/>
      <goomba level="2" amount="3"/>
      <goomba level="3" amount="3"/>
      <goomba level="4" amount="1"/>
      <goomba level="6" amount="1"/>
    </goombas>
  </levelConfiguration>
  <levelConfiguration level="29">
    <bricksDensity>0.25</bricksDensity>
    <powerup>DETONATOR</powerup>
